apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: web-pool
  template:
    metadata:
      labels:
        app: web-pool
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              memory: "112M"
              cpu: "0.1"
            limits:
              memory: "128M"
              cpu: "0.2"
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
