apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    name: nginx-cm
spec:
  containers:
    - name: nginx-cm
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/

  volumes:
    - name: config-volume
      configMap:
        name: nginx-cm
