apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: db
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: user
              name: mysql-cm
      resources:
        requests:
          memory: "1G"
          cpu: "0.5"
        limits:
          memory: "2G"
          cpu: "0.5"
    - name: wp
      image: wordpress
      resources:
        requests:
          memory: "512M"
          cpu: "0.5"
        limits:
          memory: "750M"
          cpu: "0.5"
