apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: test
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: test
  template:
    metadata:
      labels:
        environment: test
        app: nginx
    spec:
      containers:
        - name: nginx
          image: javiermanzanares/helloworld:latest
          ports:
            - containerPort: 80
