apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    project: aplication2
    environment: production
spec:
  containers:
    - name: web01
      image: nginx:1.14.2
      ports:
        - containerPort: 80
    - name: web02
      image: nginx:1.14.2
      ports:
        - containerPort: 8888
