apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    project: aplication2
    environment: developer
spec:
    containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80 
