apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret-volume
spec:
  containers:
    - name: mypod-secret-volume
      image: nginx
      volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: credential-manifest
