apiVersion: v1
kind: Pod
metadata:
  name: pod-items
spec:
  containers:
    - name: pod-items
      image: nginx
      volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: credential-manifest
        items:
          - key: username
            path: username
            mode: 500
