apiVersion: v1
kind: ReplicationController
metadata:
  name: replication01
  labels:
    project: nginx
    environment: test
spec:
  replicas: 5
  selector:
    environment: test
  template:
    metadata:
      labels:
        project: nginx
        environment: test
    spec:
      containers:
        - name: web01
          image: nginx:1.14.2
          ports:
            - containerPort: 80
