apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
    environment: test
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      app: frontend
    matchExpressions:
      - { key: environment, operator: In, values: [test] }
  template:
    metadata:
      labels:
        app: frontend
        environment: test
    spec:
      containers:
        - name: nginx
          image: javiermanzanares/helloworld:latest
          ports:
            - containerPort: 80
